### ISSUE TITLE
Review dependencies for security and outdated versions

### ISSUE THREAD

**Issue by NancyMcCallB** [iTwin/appui#231]
Review dependencies for security before release.

Validate dep and dev deps that could be updated for newer versions so we dont lag behind.

**Comment by raplemie** [comment]
# Investigation results
Removed the unused test-apps dependencies in #312, most of the remaining glaring outdated/deprecated depencencies are listed below, and will not be updated for now.

## eslint 8.x
Used version: ^7.11
Current version: 8.39.0
Status: We are relying on `@itwin/eslint-plugin` which will be ready for 8 when its 4.0.0 version actually release, before that, I dont think we should move until this is ready (we could do it with pnpmoverrides, but I'm not sure we'll be gaining much in doing so.

## jsdom 22.x
Used version: ^19.0.0
Current version: ^22.0.0
Status: 19.0 depends on deprecated `w3c-hr-time` package, however, this is closely tied to the testing and upgrading it is not a simple task for some obscure reason, this will need some investigation but it should be changed along the React 18 handling to the new testing packages version. Will not change at the moment.

### w3c-hr-time 1.0.2
This is a dependency of jsdom 19.0, no change.

## Deprecated
### circular-json 0.3.3, postinstall-build 5.0.3
These are dependencies of `typemoq`, which have seen no github activity in 6 years (5 for the maintainer) so I dont expect that to be fixed. I guess we can keep the `typemoq` package as long as we dont have any issues with it, but...

### rollup-plugin-terser 7.02, stable 0.1.8, source-map-resolve 0.5.3, source-map-url 0.4.1, urix 0.1.0, resolve-url 0.2.1, sourcemap-codec 1.4.8
As far as I can tell, these are all dependencies of react-scripts, which will likely not be updated anytime soon, since this is dev dependencies of test applications, will not update.
