### ISSUE TITLE
Error occurring while dragging and dropping Tile

### ISSUE THREAD

**Issue by muthubentley** [iTwin/appui#260]
Partner has reported error occurring while dragging and dropping Tile

**To Reproduce**
Partner has created a list of Tiles in a widget.
When the tile is dragged and dropped , then the below error is displayed:
![image](https://user-images.githubusercontent.com/107229931/230808465-52515250-cf30-4e08-ba5f-7da4c4391777.png)

**Expected behavior**
Drag and drop should work without error

**Version**
"@itwin/itwinui-react": "^2.7.0",

**Comment by raplemie** [comment]
Hi, since this is the AppUI repository, can you give us the @itwin/appui-react version of the packages that you are using?

This callstack points to the `react-dnd` package which was used in `BeDragDropContext` component and `withDragSource` and `withDragTarget` HOC's, all these were deprecated prior to the 3.0 release and should be removed from code, there is no replacement for these as they were mainly used for the previous Table interactions, which should be changed for @itwin/itwinui-react table, which do not require these.

**Comment by muthubentley** [comment]
@raplemie 
@itwin/appui-react version is 3.7.1.  I will check with partner about usage of react-dnd package and come back

**Comment by muthubentley** [comment]
@raplemie 
I confirmed that user is using react-dnd package. Do you mean this package is the reason for this error and not our iTwin packages. Is there any way to implement drag and drop using iTwin based packages?

**Comment by raplemie** [comment]
Yes, this error is coming from react-dnd package.

We are indeed not providing any solutions to implement drag drop.

Here is a list of issues related to this type of error (which havent been answered by the maintainers in years)
https://github.com/react-dnd/react-dnd/issues?q=is%3Aissue+is%3Aopen+Expected+to+find+a+valid+target

I guess other solutions should be preferred since this particular package do not seem to be actively maintained.
