### ISSUE TITLE
Loading spinner when node is loading doesn't seem to be aligned

### ISSUE THREAD

**Issue by simasjar** [iTwin/appui#358]
The loading spinner doesn't seem to be aligned when a node is loading: 
![image](https://github.com/iTwin/appui/assets/124659623/8edd436b-1d20-4515-bd43-a2f1d58dfbbb)
![image](https://github.com/iTwin/appui/assets/124659623/2ccc3417-fbbc-495b-9bf2-5e8e8a68baf1)

**To Reproduce**

1. Go to the design review with the selected larger imodel.
2. Expand and collapse any node.
3. When a node is expanding, we can see that the loading spinner is not aligned.

**Expected behavior**
Spinner to be aligned with text and other icons.

**Desktop (please complete the applicable information):**

- OS: Windows 10
- Browse: mozilla firefox

**Comment by raplemie** [comment]
@FlyersPh9 Can you have a look at the visual, my initial look into this points more towards the 
![image](https://github.com/iTwin/appui/assets/1904889/2f4429e9-4119-4e61-9e25-98428a2c28bf)
and 
![image](https://github.com/iTwin/appui/assets/1904889/905540c5-29fa-4bc4-97d4-1d14c1f2646b)
icons being too high, in comparison to the full height of the text (Eye and spinner seems aligned together and to the text, but I may be using a bad method to validate that)

**Comment by FlyersPh9** [comment]
I'm trying to reproduce using macOS current & Brave v 1.51.118.  I used the devtools to apply a gray background on the row & red on all items within the row.
![Screenshot 2023-06-13 at 5 48 12 PM](https://github.com/iTwin/appui/assets/849817/bac7e6ec-96d0-42d2-9778-f68b9eb2ba3d)
It looks like the eyeball & folder icon are misaligned but the text and expand / collapse arrow are aligned.  I am unable to color the spinner red because it disappears too soon, even with throttling set to "offline".

**Comment by raplemie** [comment]
Hi @simasjar, the issue was actually in iTwinUI component, and this was fixed in 2.12.8 ([ref](https://github.com/iTwin/iTwinUI/issues/1563#issuecomment-1721351080))

You can use this new iTwinUI package directly in your application and it should fix your issue.
