### ISSUE TITLE
ThemeManager bleeding out, if not used in root component

### ISSUE THREAD

**Issue by DenisMicha** [iTwin/appui#407]
When ThemeManager is used not in the root component, it is bleeding out. 

For example, when ThemeManager is being used just on the route for viewing iModel and the theme is set to "dark":

**Expected behavior:** the theme is dark only in the iModel view, and not outside it in the application.
**Actual behavior:** the theme is partially or fully dark in the whole application.

- iTwin.js AppUI Version 4.2.0
- iTwin.js Version 4.0.2

**Comment by raplemie** [comment]
AppUI `ThemeManager` currently sets 2 different themes, the iTwinUI theme which should be only wherever you put the application, and the AppUI theme (due to previous system). The AppUI theme is set on the `<html>` tag and is expected to affect only `AppUI` provided component (or components using our theming)

As far as I know, we dont have a short term solution/workaround to fix this. Most of the application should use iTwinUI components rather than AppUI ones, but the remaining components would require the theme to be reset when leaving the model view.

Is it common that a single application uses 2 different themes ?

**Comment by DenisMicha** [comment]
So ThemeManager always being global is not a big issue, but since there can be an impression that it can be used for a specific scope, it would be better to mention in documentation that ThemeManager is global and should only be used on a root component for clarity

**Comment by raplemie** [comment]
Hi @DenisMicha, the ThemeManager documentation was updated and released today, let me know what you think !

**Comment by DenisMicha** [comment]
> Hi @DenisMicha, the ThemeManager documentation was updated and released today, let me know what you think !
> 
> https://www.itwinjs.org/reference/appui-react/state/thememanager/

Hi @raplemie, looks good and clear now, thanks!
