### ISSUE TITLE
React and DOM states persistence on widget pop out

### ISSUE THREAD

**Issue by AAugustBentley** [iTwin/appui#524]
**Is your feature request related to a problem? Please describe.**
React and DOM state does not persist after the widget is popped out.
![image](https://github.com/iTwin/appui/assets/129863171/a99b58f4-5026-4163-976a-243be7301826)

**Describe the solution you'd like**
The React and DOM states would be kept so that the user's work would not be lost.

**Comment by raplemie** [comment]
As we don't control the Widget's structure nor the React implementation details, if this type of state is needed, maybe a solution as what React documentation describes could be done in the widget itself ?

https://react.dev/learn/preserving-and-resetting-state#preserving-state-for-removed-components

**Comment by raplemie** [comment]
We'll look if we could reuse the same strategy we use for floating widgets in popouts.

**Comment by raplemie** [comment]
Hi @AAugustBentley, a fix for this was released today as 4.7.0. Note that since your component uses iTwinUI popouts, you will need to wrap your widget content in a `<ThemeProvider theme="inherit">` component so the popout appear in the popout, we'll look into improving this in the future as #612, let us know if this addresses your issue in the mean time.

**Comment by raplemie** [comment]
HI @AAugustBentley, the solution that was implemented turned out to cause more subtle problems than it solved issues, so we reverted in 4.7.2. We will find a different solution to this issue.

**Comment by Juliakas** [comment]
We were thinking about this problem - our team would in the long run would need to have a better way to preserve state other than reinstating it from localStorage, redux or something else. If widget has a lot of internal state, in order to preserve it we would have to either expose it by props or make it use redux/context for what was supposed to be internal state. And even then there is no certainty.

Can we hook up those users #608 and #632 with event listeners whenever widget is popped out or have them use a hook that will force rerender? At least for now.

Of course this is not a trivial issue and I'm aware you need more input/suggestions/use cases from users so I would like to experiment with this further and see if any other issues appear, at least I feel like we had decent groundwork before the revert. Can we have a way to provide an "experimentalPopouts" or some other flag to continue using this feature at our own risk at `ThemeManager` or at widget level?
