### ISSUE TITLE
Change highlighted matches' style

### ISSUE THREAD

**Issue by grigasp** [iTwin/appui#562]
At the moment the `HighlightedText` component highlights text with yellow background, e.g.:
![image](https://user-images.githubusercontent.com/114080994/278314998-b8326209-32fb-4a43-a4e8-0a2bfb829f3b.gif)

UX team suggests it should be changed to transparent background and `--iui-color-text-accent` font color.

**Comment by FlyersPh9** [comment]
Can you show a screenshot of the new colors applied?  I'm worried if the background color is transparent and text is accent color that the highlighted text will look like an anchor link.

**Comment by FlyersPh9** [comment]
I chatted a little bit with @mayank99, we think that `background-color: var(--iui-color-background-accent-muted);` might work well.

Also not sure how the highlighting is working currently, but [the `<mark>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark) would work well here.

**Comment by grigasp** [comment]
I will ask @jzbuchalski and @DanAbney to jump in and express their opinion about using background vs text color. Here's an example Joe gave in our chat:
![MicrosoftTeams-image](https://github.com/iTwin/appui/assets/35135765/aeb05853-1db6-4416-a83a-1aca022d5bd6)

**Comment by raplemie** [comment]
This highlight style is defined by the browser, we use the `react-highlight-words` package which basically put a `mark` component around the specified text, the applied colors are as follows on chrome: 
<img width="285" alt="image" src="https://github.com/iTwin/appui/assets/1904889/af1f0115-5e49-46dd-a446-e111976974df">

Note that we also put a `components-activehighlight` class on the "active" highlight node, which have a `background-color: orange` definition, this might need override as well.

I doubt changing this is a good idea, since any search should probably look similar to a user (notice that if you Ctrl+F on a page, the same visual will show up, at least in chrome)

**Comment by DanAbney** [comment]
To be clear, I didn't recommend to color the text instead, I did recommend to not highlight the results in this case. However, if you still want to, maybe its better to keep it standard and see if users really DO find it distracting.

**Comment by grigasp** [comment]
I'm closing this issue. We can reopen or create a new one if anyone complains about the current styling.
