### ISSUE TITLE
The onChangeView event is no longer sent after setting up the viewport

### ISSUE THREAD

**Issue by ezmobivietnam** [iTwin/appui#631]
Hi @raplemie ,

I am experiencing an [issue](https://dev.azure.com/bentleycs/Civil-iTwin/_workitems/edit/1337383/) with the sheet index feature in which the `onChangeView` event is no longer sent after setting up the viewport. 

I was wondering if this issue has come from the PR [565](https://github.com/iTwin/appui/pull/565)? My current [solution](https://bentleycs.visualstudio.com/beconnect/_git/TCDEAppService/pullrequest/389742) is to listen to the event `onViewChanged` instead of `onChangeView`. However, it seems to be a not-good/work-around solution though.

So I would like to ask for your opinion on a solution to this issue.

Thank you!

**Comment by raplemie** [comment]
The `onChangeView` was erroneously called because we were setting the intial view state, then immediately resetting once the viewport was added, which caused an unnecessary view change to the same value, wiping all vieport change requested when the vp was received.

From what I can see, the correct way of acheiving the same thing would be through `ViewManager.onViewOpen` with a handler that will compare the viewport received from the ref with the viewOpen event argument.

Let me see if this addresses your issue.

**Comment by ezmobivietnam** [comment]
Hi @raplemie ,
Using `onViewOpen` may not address my specific use case as I noticed that the onViewOpen event is fired before the callback to set a reference to the opened viewport.
So I came up with another solution that are I will not listen to the events onViewChanged nor onViewOpen. Instead, I added a side effect to detect the setting of viewport ref callback. When receiving a viewport ref, I start setting up the viewport.

Since my PR was approved I would like to close this ticket for now.

Thank you so much for your kind help!

**Comment by raplemie** [comment]
Strange, it should not be the case as these 2 calls are made one after the other: 
<img width="432" alt="image" src="https://github.com/iTwin/appui/assets/1904889/7a14384c-778e-4942-b6d9-7db878a65567">

`viewManager.addViewport` is the code triggering the `onViewOpen`.

On the other hand, removing the overwrite that was happeing when setting up the viewport when receiving the ref was the bug to fix this in the first place (so, you previously probably used the event before and that was the workaround because of the bug :) )
