### ISSUE TITLE
Remove arrow visual component from `StatusBarPopup`

### ISSUE THREAD

**Issue by GerardasB** [iTwin/appui#707]
**Is your feature request related to a problem? Please describe.**
Currently, the arrow of a `StatusBarPopup` that is pointing to a status bar field is not always centered on the entry point.

**Describe the solution you'd like**
Remove the arrow of a `StatusBarPopup`.

**Before:**
![image](https://github.com/iTwin/appui/assets/849817/b97515f1-a5e2-40e4-acac-9f1cbb6a3247)

**After:**
![image](https://github.com/iTwin/appui/assets/849817/ce38a070-323c-46cd-878e-4799c83583a7)

**Comment by mayank99** [comment]
This issue was closed via #750, however there is room for improvement. Ideally there would be a way to indicate which button triggered the Popup (likely needs new styling, because the blue color is reserved for active/"selected" state).

Also we were also talking about reintroducing the arrow in iTwinUI. The condition there of course is that the arrow should be centered relative to the trigger, not the popup.
