### ISSUE TITLE
Widget content effects fire before it is actually rendered in widget

### ISSUE THREAD

**Issue by Juliakas** [iTwin/appui#762]
### Describe the bug

This is more noticeable when I navigate between frontstages - to reproduce issue widget in question should not be present in another frontstage because it needs to be unmounted first.

When rendering react component as widget contents, all effects are being fired before widget is actually visible in widget DOM. When observing it with breakpoints at `useEffect`/`useLayoutEffect` I can only see this when under highlighted element I expect to see rendered content:
![image](https://github.com/iTwin/appui/assets/36437897/5aad5fbf-8403-4ad1-8238-98f0ffd2bb6b)

This messes up layout in cases where effects were making changes to DOM or when it requires DOM to make calculations. I investigated further and used MutationObserver to confirm that widget content is actually being appended after effects fire (ContentRenderer.tsx):
![image](https://github.com/iTwin/appui/assets/36437897/6e304c10-d162-4694-b172-3971ae6db064)
___
Which is called because of (FrontstageDef.tsx):
![image](https://github.com/iTwin/appui/assets/36437897/d9850657-3ca4-4102-b467-469f8d1850bc)

### To Reproduce

1. Open test app with at least 2 frontstages, one fronstage has a widget that has `useEffect` in it.
2. Set breakpoint for effect and navigate between frontstages.
3. Inspect elements tree and notice widget is not actually placed inside DOM yet even though effect fired already.

### Expected Behavior

DOM is already rendered before effects fire.

### Desktop (please complete the applicable information)

- **OS:** Windows
- **Browser:** Electron
- **Version:** 25.8.1 (npm version)
- **iTwin.js AppUI Version:** 4.10.0
- **iTwin.js Version:** 4.4.3

**Comment by GerardasB** [comment]
That is correct, we are reparenting widget content DOM node to display widget content in different parts of the UI (i.e. different panel sections or floating widgets).
React element tree is stable per frontstage to prevent re-mounts when moving/docking/merging widgets in the UI.
Widget react nodes are loaded first and are portaled to a detached DOM element (which is what you are observing).
I.e. widget rendered w/ `WidgetState.Hidden` will run all React lifecycle methods (like `useEffect`, but the DOM element will not be added to the page).

We have a custom hook [useTransientState](https://www.itwinjs.org/reference/appui-react/widget/usetransientstate/) that you can use to save/restore DOM properties that are not persisted when element parent is changed (like scroll position).
The function `onSave` is called before removing widget content DOM node and `onRestore` is called after appending the DOM node.

I think you could utilize `useTransientState` hook for your use case as well (instead of doing your calculations in `useEffect`, do them in `onRestore`). Would that work for you?

Could you describe a little more your use-case, what calculation are you doing and what are you trying to accomplish?

**Comment by GerardasB** [comment]
Yeah, widget content is currently re-mounted when popout is opened. I think we should still be calling `onSave`/`onRestore` when popout is opened/closed.
Alternatively, we have this issue https://github.com/iTwin/appui/issues/524 for which the plan is to put https://github.com/iTwin/appui/pull/606 changes under a preview feature flag.
