### ISSUE TITLE
Frontstage is missing registered widgets

### ISSUE THREAD

**Issue by bilalbaig3101** [iTwin/appui#778]
### Describe the bug

While upgrading itwin/presentation-component to 5.0.0. On doing so, I upgraded itwinjs-core to 4.4.0, appui to 4.9.0, and itwinui-react to 3. On app start, the viewer stage opens without the widgets, and on reopening, it shows the widgets.
migration guideline: [https://github.com/iTwin/presentation/wiki/5.x-migration-guide#breaking-changes](url)
Project: Studio
Branch link: [https://github.com/iTwin/studio/tree/bilal/upgrade-presentation-component](url)

### To Reproduce

- pnpm i
- pnpm build
- cd packages/framework
- pnpm start (desktop app will launch)
- select project
- select imodel

### Screenshots

**First time (without widgets)**
![image](https://github.com/iTwin/appui/assets/76512164/d4011902-be67-45c4-a25c-efb0993446c1)
**Other times (with widgets)**
![image](https://github.com/iTwin/appui/assets/76512164/665c6081-2f4c-457f-a512-6884b02bcaea)

**Comment by johnnyd710** [comment]
I believe this is caused because of [where we call `loadUiItems` in the visualizer app](https://github.com/iTwin/studio/blob/main/packages/apps/itwin-studio-visualizer/frontend/frontstages/Visualizer.tsx#L140). If we register ui items earlier (e.g., during app startup) the issue will be resolved. Any idea why?

**Comment by GerardasB** [comment]
Haven't had the chance to debug it yet, but I'll try and register a provider from content group getter.
