### ISSUE TITLE
Popups - dialogs appearing below the popped out widget

### ISSUE THREAD

**Issue by jzbuchalski** [iTwin/appui#962]
### Describe the bug

If a widget is popped out (on a single monitor), any dialog shown from that popped out widget will appear below the popout.

### Expected Behavior

Should appear above the popped out widget.

### Screenshots

![image](https://github.com/user-attachments/assets/02d7fa7f-f499-4912-9f15-1264c902de6b)

**Comment by ignas-k** [comment]
I assume your widget uses `UiFramework.dialogs.modal.open` which is an old API therefore it is slightly problematic. Unfortunately, there isn't anything we can do to fix this, however, you can fix this issue yourselves: 

- The best way to solve this would be to use `Dialog` from iTwinUI instead of the `UiFramework.dialogs.modal.open` function. This API was created before the iTwinUI dialogs existed so they are the new and preferred way to render dialogs. Note: you have to pass `portal` property to `Dialog` for it be portaled into the popout widget.
- If you do not want to use the iTwinUI `Dialog`, you can pass a `parentDocument` property when calling `UiFramework.dialogs.modal.open` e.g. you can create a ref for the button that opens the dialog and pass the `ref.current.ownerDocument` value as the third property in `UiFramework.dialogs.modal.open`.

**Comment by jzbuchalski** [comment]
Excellent, we will give these suggestions a try.
