### ISSUE TITLE
No padding for Selection Count right side when NOT on far right of status bar

### ISSUE THREAD

**Issue by wilmaier** [iTwin/appui#978]
### Describe the bug

As of appui 4.16.1, the selection count padding contains a fix which adds padding when it is the rightmost item on the status bar.  However, if it is in the middle somewhere, there is no padding added after the fixed min-width (5 digits) as shown below in screen capture.

### To Reproduce

Open any iModel and select more than 10000 elements.
Note that the status bar selection count field shows the count with no padding on right side

### Expected Behavior

Added this workaround which produces a good result  (shown in second screenshot below):

.uifw-statusFields-selectionCount {
  padding-right: var(--iui-size-xs) !important;
}

### Screenshots

Issue:
![image](https://github.com/user-attachments/assets/dfffc5a6-bb3d-4800-a6e1-38de9d95204e)

Suggested fix:
![image](https://github.com/user-attachments/assets/d82bd133-ecc1-4acb-90a8-6b893b6b2954)

**Comment by ignas-k** [comment]
This is a bit of an edge case because the selection count is in 6 digits and you're using a separator (which removes the padding between different status bar fields) after it. Despite that I still believe this request is valid so we will release a fix in the next minor/patch. However, for the future please note two things:

- When a component is a part of a more complex system (like the status bar) it is almost impossible to predict and make adjustments for all edge cases. It is good that you inform us of this and sometimes we can fix it but that may not be the case if the changes does not make sense to AppUI even if it makes sense for you. This leads to the next point:
- If you need more individual control of our status bar components you can always use the components directly and put them in your custom providers instead of using our standard providers. This gives you way more control of the component and you can easily make styling adjustments by passing `className` or `style` props to it. Using selectors to target our classNames is not a good solution.
